#!/bin/bash
#
# Bookmarked bash commands
#
# Select a command to run it
#

#
# Define functions
#

containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

#
# Main script
#

# bookmark file path
file="$HOME/.xmonad/.dmenu_bookmarks.txt"

# get the number of lines in the file
height=$(wc -l "$file" | awk '{print $1}')

# read the contents of the file in a bash array
readarray -t options < "$file"

prompt="Select a bookmark: "
font="monofur-10"

choice=$(printf '%s\n' "${options[@]}" | dmenu -l "$height" -p "$prompt" -fn "$font")

echo $choice

if $(containsElement "$choice" "${options[@]}") ; then
    command=$(echo "${choice}" | awk -F ' : ' '{print $NF}')
    $command
else
    printf '%s\n' "Option does not exist"
fi
