#!/bin/bash
#
# Open file from zotero storage without launching zotero
#

#
# Main script
#

# zotero storage folder
storage_dir="$HOME/google_drive_encr/UCB/research/resources/notes/formulas/"
# pdf files
files=$(find $storage_dir -name '*.pdf' | sort)
# height=$(find $storage_dir -name *.pdf | wc -l)  # huge
# dmenu IO
font="Serif-9"
prompt="Select a file: "
choice=$(printf '%s\n' "$files" | dmenu -i -l "20" -p "$prompt" -fn "$font")

xdg-open "$choice"
